unit backups;

interface

procedure Backup_Log;
procedure Init_Backups;  

function UploadBackup(thefile,theserv,theuser,thepass:string):boolean;
function DownloadBackup(theserv,theuser,thepass:string):string;

procedure Make_BackUp(fromfolder,thefile:string);
function  Full_BackUp:string; 
function Restore_Backup(thefile:string):string;
procedure Full_Program_BackUp;
procedure LastBackupNow; 
procedure SetLastBackupFilename(dat:string);
function GetLastBackupFilename:string;
function GetLastBackup:integer;
procedure SetLastBackup(dat:integer);
function NeedBackup:boolean;

implementation 
uses windows,ammarunit,userlogin,calender,settings,tools,string_stuff;

var curendir:string;
    last_backup:integer;
    last_backup_filename:string;




procedure Backup_Log;
var fileused:file of byte;
    datesnstuff:array[1..4]of word;
    new_name:string;
begin
assign(fileused,curendir+'log.dat');
{$i-}
reset(fileused);
{$i+}
if ioresult=0 then
begin
if (FileSize(fileused) div 1024)>512 then begin
                                           close(fileused);
                                           GetLDate(datesnstuff[1],datesnstuff[2],datesnstuff[3],datesnstuff[4]); 
                                           new_name:='log_'+Convert2String(datesnstuff[1])+'_'+Convert2String(datesnstuff[3])+'_'+Convert2String(datesnstuff[4])+'.dat';
                                           OuttextCenter('Backing up log...');
                                           CopyFile(curendir+'log.dat',curendir+'Backup\'+new_name);
                                           rewrite(fileused); 
                                          end;
close(fileused); 
end;
end;


procedure Make_BackUp(fromfolder,thefile:string);
var datesnstuff:array[1..8]of word;
    epithema:string;
begin
GetLDate(datesnstuff[1],datesnstuff[2],datesnstuff[3],datesnstuff[4]);
GetLTime(datesnstuff[5],datesnstuff[6],datesnstuff[7],datesnstuff[8]);
epithema:=Convert2String(datesnstuff[1])+'_'+Convert2String(datesnstuff[3])+'_'+Convert2String(datesnstuff[4]);
epithema:=epithema+Convert2String(datesnstuff[5])+'_'+Convert2String(datesnstuff[6])+'_';
Write_2_Log('System Backing up '+fromfolder+'\'+thefile);
CopyFile(curendir+fromfolder+'\'+thefile,curendir+'Backup'+'\'+fromfolder+'\'+epithema+thefile); 
end;




procedure LastBackup(thed,them,they:integer);
begin
last_backup:=Calender_Function(thed,them,they,0);
end;

procedure LastBackupNow; 
var datesnstuff:array[1..4]of word;
begin
GetLDate(datesnstuff[1],datesnstuff[2],datesnstuff[3],datesnstuff[4]); 
LastBackup(datesnstuff[1],datesnstuff[3],datesnstuff[4]);
end;

function GetLastBackupFilename:string;
begin
GetLastBackupFilename:=last_backup_filename;
end;

procedure SetLastBackupFilename(dat:string);
begin
last_backup_filename:=dat;
end;


function GetLastBackup:integer;
begin
GetLastBackup:=last_backup;
end;

procedure SetLastBackup(dat:integer);
begin
last_backup:=dat;
end;

function NeedBackup:boolean;
var retres:boolean;
    days_timeout,i:integer;
    datesnstuff:array[1..4]of word;
begin
retres:=false;
GetLDate(datesnstuff[1],datesnstuff[2],datesnstuff[3],datesnstuff[4]);
Val(get_setting(4),days_timeout,i);
if Calender_Function(datesnstuff[1],datesnstuff[3],datesnstuff[4],0)-last_backup>days_timeout then retres:=true;
NeedBackup:=retres;
end;



function UploadBackup(thefile,theserv,theuser,thepass:string):boolean;
var fileused:text;
    retres:boolean;
    prog_pack_dir,bufstr:string;
begin
retres:=false;
Write_2_Log('Uploading an internet backup ..!');
prog_pack_dir:=AnalyseFilename(get_external_synctool,'directory');
Write_2_Log('Generating Script');
delete_file(get_central_dir+'Backup\onlinebackup.apf');
assign(fileused,prog_pack_dir+'script.txt');
{$i-}
rewrite(fileused);
{$i+}
if Ioresult<>0 then MessageBox (0, 'Could not create backup script..!' , 'Backup Subsystem', 0 + MB_ICONEXCLAMATION) else
 begin
   Write_2_Log('Clearing Transactions File');
   clear_file(prog_pack_dir+'transactions.txt');
   Write_2_Log('Script file opened'); 
   writeln(fileused,'connect(FTP,',theserv,',',theuser,',off)');
   writeln(fileused,'file(upload,"'+get_central_dir+'Backup\'+thefile+'","onlinebackup.apf",0)');
   writeln(fileused,'disconnect');
   writeln(fileused,'#That`s it');
   writeln(fileused,'#Script generated by DDmk2 , written by Ammar Qammaz');
   close(fileused);
   Write_2_Log('Script Ready');

   retres:=true;
   
   //SetCurrentDirectory(Pchar(prog_pack_dir));
   chdir(prog_pack_dir);
   RunEXEWait(get_external_synctool+' -p '+thepass,false);
   delay(500);
   clrscreen;
   chdir(curendir);


   //CHECK IF OPERATION SUCCEDDED
   assign(fileused,prog_pack_dir+'transactions.txt');
   {$i-}
    reset(fileused);
   {$i+}
    if Ioresult<>0 then begin end else
     begin
      readln(fileused,bufstr);
      seperate_words(bufstr);
      if not (Equal(get_memory(1),'upload')) then retres:=false;
      close(fileused);
     end;
   //CHECK IF OPERATION SUCCEDDED

 end; 
UploadBackup:=retres;
end;


function DownloadBackup(theserv,theuser,thepass:string):string;
var fileused:text;
    retres,bufstr,prog_pack_dir:string;
begin
retres:='';
Write_2_Log('Downloading an internet backup ..!'); 
prog_pack_dir:=AnalyseFilename(get_external_synctool,'directory');
Write_2_Log('Generating Script');
delete_file(get_central_dir+'Backup\onlinebackup.apf');
assign(fileused,prog_pack_dir+'script.txt');
{$i-}
rewrite(fileused);
{$i+}
if Ioresult<>0 then MessageBox (0, 'Could not create backup script..!' , 'Backup Subsystem', 0 + MB_ICONEXCLAMATION) else
 begin
   Write_2_Log('Clearing Transactions File');
   clear_file(prog_pack_dir+'transactions.txt');
   Write_2_Log('Script file opened');
   writeln(fileused,'connect(FTP,',theserv,',',theuser,',off)');
   writeln(fileused,'file(download,"'+get_central_dir+'Backup\onlinebackup.apf'+'","onlinebackup.apf",0)');
   retres:=get_central_dir+'Backup\onlinebackup.apf';
   writeln(fileused,'disconnect');
   writeln(fileused,'#That`s it');
   writeln(fileused,'#Script generated by DDmk2 , written by Ammar Qammaz');
   close(fileused);
   Write_2_Log('Script Ready');

   //SetCurrentDirectory(Pchar(prog_pack_dir));
   chdir(prog_pack_dir);
   Write_2_Log('Running Synchronizer Tool');
   RunEXEWait(get_external_synctool+' -p '+thepass,false);
   delay(500);
   clrscreen;
   chdir(curendir);

   //CHECK IF OPERATION SUCCEDDED
   assign(fileused,prog_pack_dir+'transactions.txt');
   {$i-}
    reset(fileused);
   {$i+}
    if Ioresult<>0 then begin end else
     begin
      readln(fileused,bufstr);
      seperate_words(bufstr);
      if not (Equal(get_memory(1),'download')) then retres:='';
      close(fileused);
     end;
   //CHECK IF OPERATION SUCCEDDED
   

 end; 
DownloadBackup:=retres;
end;









  // seed=((seed*20)+10) /2;

function Full_BackUp:string;
var datesnstuff:array[1..4]of word;
    prog_pack_dir,retres:string;
    fileused:text;
    label end_backup;
begin
retres:='';
if (not is_master_computer) then begin
                                  MessageBox (0, 'Η λειτουργία αυτή εκτελείται μόνο από τον κεντρικό υπολογιστή..' , 'Απαγορευμένη Λειτουργία..', 0 + MB_ICONASTERISK);
                                  goto end_backup;
                                 end else
if (Get_User_Access(Get_Current_User)<500) then
                                 begin
                                  MessageBox (0, 'Η λειτουργία αυτή χρειάζεται κωδικό μεγαλύτερης πρόσβασης (500)..' , 'Απαγορευμένη Λειτουργία..', 0 + MB_ICONASTERISK);
                                  goto end_backup;
                                 end;

Write_2_Log('Making a full backup ..!');
GetLDate(datesnstuff[1],datesnstuff[2],datesnstuff[3],datesnstuff[4]);
prog_pack_dir:=AnalyseFilename(get_external_packer,'directory'); 
assign(fileused,prog_pack_dir+'script.txt');
{$i-}
rewrite(fileused);
{$i+}
if Ioresult<>0 then MessageBox (0, 'Could not create backup script..!' , 'Backup Subsystem', 0 + MB_ICONEXCLAMATION);
//writeln(fileused,'silent()');
writeln(fileused,'beginlist()');
writeln(fileused,'PRESERVE_DIRECTORY_TREE=on');
//writeln(fileused,'adddir('+prog_pack_dir+')');
writeln(fileused,'chdir('+curendir+')');
writeln(fileused,'adddir('+curendir+'Users\)');
writeln(fileused,'adddir('+curendir+'Database\)');
writeln(fileused,'adddir('+curendir+'Calender\)');
writeln(fileused,'optimize(size)');
writeln(fileused,'compress(on)');
writeln(fileused,'chdir_out('+curendir+'Backup\'+')');
retres:='fullbackup'+Convert2String(datesnstuff[1])+'-'+Convert2String(datesnstuff[3])+'-'+Convert2String(datesnstuff[4])+'.apf';
SetLastBackupFilename(curendir+'Backup\'+retres);
writeln(fileused,'pack('+retres+')');
LastBackup(datesnstuff[1],datesnstuff[3],datesnstuff[4]);
close(fileused);
//RunEXE(prog_pack_dir+'AmmarPack.exe','normal');
OutTextCenter('Backing Up');
chdir(prog_pack_dir);
if (not RunExeWait(get_external_packer,true)) then
  //MakeMessageBox (Pchar('Problem Calling '+get_external_packer) , ' ', '' ,'','');
  MakeMessageBox(
  PAnsiChar(AnsiString('Problem Calling ' + get_external_packer)),
  PAnsiChar(AnsiString(' ')),
  PAnsiChar(AnsiString('')),
  PAnsiChar(AnsiString('')),
  PAnsiChar(AnsiString(''))
);

chdir(curendir);

OutTextCenter('Success..');
//MakeMessageBox('Backup..','Πατήστε OK όταν τελειώσει η διαδικασία backup','','','SYSTEM');
Write_2_Log('Full backup complete ..!');
//delay(2000);
end_backup:
Full_BackUp:=retres;
end;



function Restore_Backup(thefile:string):string;
var datesnstuff:array[1..4]of word;
    prog_pack_dir:string;
    fileused:text;
    label end_backup;
begin 
if (not is_master_computer) then begin
                                  MessageBox (0, 'Η λειτουργία αυτή εκτελείται μόνο από τον κεντρικό υπολογιστή..' , 'Απαγορευμένη Λειτουργία..', 0 + MB_ICONASTERISK);
                                  goto end_backup;
                                 end else
if (Get_User_Access(Get_Current_User)<500) then
                                 begin
                                  MessageBox (0, 'Η λειτουργία αυτή χρειάζεται κωδικό μεγαλύτερης πρόσβασης (500)..' , 'Απαγορευμένη Λειτουργία..', 0 + MB_ICONASTERISK);
                                  goto end_backup;
                                 end;
Write_2_Log('Restoring backup '+thefile+'..!');
GetLDate(datesnstuff[1],datesnstuff[2],datesnstuff[3],datesnstuff[4]);
prog_pack_dir:=AnalyseFilename(get_external_packer,'directory'); 
assign(fileused,prog_pack_dir+'script.txt');
{$i-}
rewrite(fileused);
{$i+}
if Ioresult<>0 then MessageBox (0, 'Could not create backup restoration script..!' , 'Backup Subsystem', 0 + MB_ICONEXCLAMATION);
//writeln(fileused,'silent()');
writeln(fileused,'beginlist()');
writeln(fileused,'PRESERVE_DIRECTORY_TREE=on');
//writeln(fileused,'adddir('+prog_pack_dir+')');
writeln(fileused,'optimize(size)');
writeln(fileused,'compress(on)');
writeln(fileused,'chdir('+curendir+'Backup\'+')');
writeln(fileused,'chdir_in('+curendir+'Backup\'+')');
writeln(fileused,'chdir_out('+curendir+')');
writeln(fileused,'unpack('+thefile+')'); 
close(fileused); 
OutTextCenter('Restoring BackUp');
chdir(prog_pack_dir);
if (not RunExeWait(get_external_packer,true)) then
  //MakeMessageBox (Pchar('Problem Calling '+get_external_packer) , ' ', '' ,'','');
  MakeMessageBox(
  PAnsiChar(AnsiString('Problem Calling ' + get_external_packer)),
  PAnsiChar(AnsiString(' ')),
  PAnsiChar(AnsiString('')),
  PAnsiChar(AnsiString('')),
  PAnsiChar(AnsiString(''))
);

chdir(curendir);

OutTextCenter('Success..');
//MakeMessageBox('Backup..','Πατήστε OK όταν τελειώσει η διαδικασία backup','','','SYSTEM');
Write_2_Log('Full restore complete ..!');
//delay(2000);
end_backup:
Restore_Backup:=thefile;
end;




procedure Full_Program_BackUp;
var datesnstuff:array[1..4]of word;
    prog_pack_dir,bufstr:string;
    fileused:text;
    label end_backup;
begin
if (not is_master_computer) then begin
                                  MessageBox (0, 'Η λειτουργία αυτή εκτελείται μόνο από τον κεντρικό υπολογιστή..' , 'Απαγορευμένη Λειτουργία..', 0 + MB_ICONASTERISK);
                                  goto end_backup;
                                 end else
if (Get_User_Access(Get_Current_User)<500) then
                                 begin
                                  MessageBox (0, 'Η λειτουργία αυτή χρειάζεται κωδικό μεγαλύτερης πρόσβασης (500)..' , 'Απαγορευμένη Λειτουργία..', 0 + MB_ICONASTERISK);
                                  goto end_backup;
                                 end;
Write_2_Log('Making a program backup ..!');
GetLDate(datesnstuff[1],datesnstuff[2],datesnstuff[3],datesnstuff[4]);
prog_pack_dir:=AnalyseFilename(get_external_packer,'directory'); 
assign(fileused,prog_pack_dir+'script.txt');
{$i-}
rewrite(fileused);
{$i+}
if Ioresult<>0 then begin
                     MessageBox (0, 'Error Backing up.. Could not create script..' , 'Backup Subsystem', 0 + MB_ICONASTERISK);
                     goto end_backup;
                    end;
//writeln(fileused,'silent()');
writeln(fileused,'beginlist()');
writeln(fileused,'PRESERVE_DIRECTORY_TREE=on');
//writeln(fileused,'adddir('+prog_pack_dir+')');
chdir(curendir);
chdir('..');
getdir(0,bufstr);
if bufstr[Length(bufstr)]<>'\' then bufstr:=bufstr+'\';
writeln(fileused,'chdir('+bufstr+')');
writeln(fileused,'adddir('+bufstr+'Dental Database Mk2\)');
//MakeMessageBox ('', pchar(bufstr+'Dental Database Mk2\') , ' ', '' ,'');
writeln(fileused,'optimize(size)');
writeln(fileused,'compress(on)');
writeln(fileused,'chdir_out('+curendir+'..\Dental Database Mk2 History\'+')');
writeln(fileused,'pack(programbackup'+Convert2String(datesnstuff[1])+'-'+Convert2String(datesnstuff[3])+'-'+Convert2String(datesnstuff[4])+'.apf)');
SetLastBackupFilename(curendir+'..\Dental Database Mk2 History\programbackup'+Convert2String(datesnstuff[1])+'-'+Convert2String(datesnstuff[3])+'-'+Convert2String(datesnstuff[4])+'.apf)');
// -> DISABLED <- LastBackup(datesnstuff[1],datesnstuff[3],datesnstuff[4]);
close(fileused);
//RunEXE(prog_pack_dir+'AmmarPack.exe','normal');
OutTextCenter('Backing Up');
chdir(prog_pack_dir);
if (not RunExeWait(get_external_packer,true)) then
  //MakeMessageBox (Pchar('Problem Calling '+get_external_packer) , ' ', '' ,'','');
  MakeMessageBox(
  PAnsiChar(AnsiString('Problem Calling ' + get_external_packer)),
  PAnsiChar(AnsiString(' ')),
  PAnsiChar(AnsiString('')),
  PAnsiChar(AnsiString('')),
  PAnsiChar(AnsiString(''))
);

chdir(curendir);

OutTextCenter('Success..');
//MakeMessageBox('Backup..','Πατήστε OK όταν τελειώσει η διαδικασία backup','','','SYSTEM');
Write_2_Log('Full backup complete ..!');
end_backup:
//delay(2000);
end;

  
procedure Init_Backups;
begin
GetDir(0,curendir); 
if curendir[Length(curendir)]<>'\' then curendir:=curendir+'\';
last_backup_filename:='';
end;


begin
end.
