unit people_help;

interface
 
function Select_GUI_Smiley(theword:string):string;
procedure Show_Plans(thefile:string);
 
implementation 
uses windows,ammarunit,ammargui,apsfiles,string_stuff,people,userlogin,the_works,backups,settings,teeth,calender;
const MAX_SXEDIA=15;
      MAX_SXEDIA_PARTS=128;
Type
 PlanPart =
  Record
   work_id : string;
   price : integer;
   discount : integer;
   prepayment : integer;
   dontia:string;
   arithmos_dontiwn : integer;
   comments:string;
   comments2:string;
   doctor:string;
   explain_file:string; 
   dateday : integer;
   datemonth : integer;
   dateyear : integer;
   datehour : integer;
   datemin : integer; 
   date_set:boolean;
   used:boolean;
  End;

var sxedia_aliases_addr:array[1..2,1..MAX_SXEDIA] of integer; //dieythinseis sxediwn
    sxedia_aliases:array[1..MAX_SXEDIA] of string;
    sxedia_data:array[1..MAX_SXEDIA_PARTS] of PlanPart;
    aliases_count,last_data:integer;
    tmp_plan:PlanPart;
    the_plan_file:string;
function Select_GUI_Smiley(theword:string):string;
const MAX_SMILIES=13;
var i,xcount,ycount,startx,starty,blockx,space,blocky:integer;
    aps2load,lastobj,retres:string;
    smilies:array[1..MAX_SMILIES] of string;
begin 
retres:=theword;
smilies[1]:='smiley_confused' ;
smilies[2]:='smiley_unhappy' ;
smilies[3]:='smiley_question' ;
smilies[4]:='smiley_neutral' ;
smilies[5]:='smiley_mad' ;
smilies[6]:='smiley_ntropalos' ;
smilies[7]:='smiley_idea' ;
smilies[8]:='smiley_happy' ;
smilies[9]:='smiley_exclaim' ;
smilies[10]:='smiley_frown' ;
smilies[11]:='smiley_evil' ;
smilies[12]:='smiley_eek';
smilies[13]:='smiley_surprised';


startx:=(GetMaxX div 2)-150;
starty:=200;
space:=15;
blockx:=GetApsInfo('smiley_confused','sizex');
blocky:=GetApsInfo('smiley_confused','sizey');

include_object('GUI_Select_Icon','window','Επιλογή χρήστη','GUI_Select_User','','',startx,starty,startx+300,starty+blocky*12);
draw_all; 
flush_gui_memory(0);

starty:=starty+50;
xcount:=0;
ycount:=0;
for i:=1 to 13 do begin
                    xcount:=xcount+1;
                    if xcount=6 then begin
                                      xcount:=0;
                                      ycount:=ycount+1;
                                     end;

                    aps2load:=smilies[i];
                    include_object('GUI_Select_Icon('+Convert2String(i),'layer','1','GUI_Select_Icon','','',startx+(xcount+3)*(blockx+space),starty+ycount*(blocky+space),startx+blockx+(xcount+3)*(blockx+space),starty+blocky+ycount*(blocky+space));
                    DrawApsXY(aps2load,startx+(xcount+3)*(blockx+space),starty+ycount*(blocky+space));
                  end;
include_object('ok','buttonc','ΟΚ','GUI_Select_Icon','','',-1,starty+blocky*5,-1,0);
draw_all;

repeat
interact;
lastobj:=return_last_mouse_object;  
if get_object_data(lastobj)='4' then begin
                                      seperate_words(lastobj);
                                      if Equal('GUI_Select_Icon',get_memory(1)) then
                                       begin
                                        retres:=smilies[get_memory_int(2)];
                                        break;
                                       end;

                                     end;
until get_object_data('ok')='4';

Select_GUI_Smiley:=retres;
end;



function Print_Plan(the_alias:integer):string;
var retres,startdir:string;
    fileused:text;
    total_price,sumpay,sumprice,sumdiscount,discount2euro,i:integer;
    show_discount:boolean;
begin
getdir(0,startdir);
chdir(People_Data(0)+'Cache'); //People_Data(0) =curendir
retres:=People_Data(2)+'_plan_'+Convert2String(the_alias)+'.html';
assign(fileused,retres);
rewrite(fileused);
writeln(fileused,'<html><!--GENERATED BY DENTAL_DATABASE :)-->');
writeln(fileused,'<head>');
writeln(fileused,'<title>Σχέδιο '+Convert2String(the_alias)+'/'+Convert2String(aliases_count)+' για '+People_Data(2)+' '+People_Data(3)+'</title>');
writeln(fileused,'<meta http-equiv="Content-Type" content="text/html; charset=windows-1253">');
writeln(fileused,'</head>');
writeln(fileused,'<body bgcolor=#FFFFFF text=#000000>');
writeln(fileused,'<center>');
writeln(fileused,'<img src="../logo.jpg" width=500> <font bgcolor=#CCCCCC size=1>Powered by A-TECH</font><br><br>');
writeln(fileused,'<h2> Σχέδιο εργασιών '+Convert2String(the_alias)+'/'+Convert2String(aliases_count)+'</h2>');
writeln(fileused,'<h2> για '+People_Data(2)+' '+People_Data(3)+'</h2>');
writeln(fileused,'<br><br><br>');
writeln(fileused,'<hr><table border=1>');
show_discount:=false;
for i:=sxedia_aliases_addr[1,the_alias] to sxedia_aliases_addr[2,the_alias] do
 begin
  if sxedia_data[i].discount<>0 then show_discount:=true;
 end;                          //<td>Προκαταβολή</td><td>Δόσεις</td>
writeln(fileused,'<tr><td>Εργασία</td><td>Οδοντίατρος</td><td>Αρ.δοντιού</td><td>Τιμή ομάδας</td><td>Ποσότητα</td><td>Αξία</td>');
if show_discount then writeln(fileused,'<td>Έκπτωση</td>');
writeln(fileused,'<td>Τελική αξία</td><td>Περιγραφή</td></tr>');

sumpay:=0;
sumprice:=0;
sumdiscount:=0;


for i:=sxedia_aliases_addr[1,the_alias] to sxedia_aliases_addr[2,the_alias] do
  begin
    total_price:=sxedia_data[i].arithmos_dontiwn*sxedia_data[i].price;
    sumprice:=sumprice+(sxedia_data[i].arithmos_dontiwn*sxedia_data[i].price);
    sumpay:=sumpay+sxedia_data[i].prepayment;
    discount2euro:=(total_price*sxedia_data[i].discount)div 100;
    if sxedia_data[i].discount<>0 then begin 
                                          sumdiscount:=sumdiscount+discount2euro;
                                       end;
    writeln(fileused,'<tr><td>'+sxedia_data[i].work_id+'</td><td>'+Get_User_Data(3,Get_User_Number(sxedia_data[i].doctor))+'</td>');
                                                         //<td>'+Convert2String(sxedia_data[i].prepayment)+'</td><td>'+Convert2String(sxedia_data[i].doseis)+'</td>'
    writeln(fileused,'<td>'+sxedia_data[i].dontia+'&nbsp;</td>');
    writeln(fileused,'<td>'+Convert2String(sxedia_data[i].price)+' &euro;</td>');
    writeln(fileused,'<td><center>'+Convert2String(sxedia_data[i].arithmos_dontiwn)+'x</center></td>');
    writeln(fileused,'<td>'+Convert2String(total_price)+' &euro;</td>');
    if show_discount then begin
    if sxedia_data[i].discount<>0 then writeln(fileused,'<td>'+Convert2String(discount2euro)+' &euro; ('+Convert2String(sxedia_data[i].discount)+'%)</td>') else
                                       writeln(fileused,'<td><center>-</center></td>'); //NO DISCOUNT
                          end;
    writeln(fileused,'<td>'+Convert2String(total_price-discount2euro)+' &euro;</td>' );
    writeln(fileused,'<td>'+sxedia_data[i].comments+' '+sxedia_data[i].comments2+'</td></tr>'); 
  end; 
writeln(fileused,'<tr><td colspan=5>Σύνολο</td><td>'+Convert2String(sumprice)+'&euro;</td>');
if show_discount then writeln(fileused,'<td>'+Convert2String(sumdiscount)+'&euro;</td>');
writeln(fileused,'<td>'+Convert2String(sumprice-sumdiscount)+'&euro;</td><td>&nbsp;</td></tr>');
writeln(fileused,'</table><hr>');
writeln(fileused,'</center>');
writeln(fileused,'</body>');
writeln(fileused,'</html>');
close(fileused);
chdir(startdir); 
Print_Plan:=retres;
end;


//PEOPLE HELP SXEDIA ASTHENWN
procedure clr_tmp_plan;
begin
tmp_plan.work_id:='';
tmp_plan.price:=0;
tmp_plan.discount:=0;
tmp_plan.prepayment:=0;
tmp_plan.dontia:='';
tmp_plan.arithmos_dontiwn:=0;
//tmp_plan.doseis:=0;
tmp_plan.comments:='';
tmp_plan.comments2:='';
tmp_plan.doctor:='';
tmp_plan.explain_file:='';
tmp_plan.dateday:=0;
tmp_plan.datemonth:=0;
tmp_plan.dateyear:=0;
tmp_plan.datehour:=0;
tmp_plan.datemin:=0;
tmp_plan.date_set:=false;
tmp_plan.used:=false;
end;


function alias_is_correct(the_alias:integer):boolean;
var retres:boolean;
label end_check;
begin
retres:=true;
if the_alias<0 then begin
                     Write_2_Log('ERROR - the_alias out is <1 in alias_is_correct..');
                     retres:=false;
                     goto end_check;
                    end else
if the_alias>MAX_SXEDIA then begin
                              Write_2_Log('ERROR - the_alias out is >MAX_SXEDIA in alias_is_correct..');
                              retres:=false;
                              goto end_check;
                             end;

if sxedia_aliases_addr[1,the_alias]<1 then begin
                                             Write_2_Log('ERROR - sxedia_aliases_addr[1,the_alias]<1 in alias_is_correct..');
                                             retres:=false;
                                             goto end_check;
                                           end else
if sxedia_aliases_addr[2,the_alias]>MAX_SXEDIA_PARTS then begin
                                                           Write_2_Log('ERROR - sxedia_aliases_addr[2,the_alias]>MAX_SXEDIA_PARTS in alias_is_correct..');
                                                           retres:=false;
                                                           goto end_check;
                                                          end;
if sxedia_aliases_addr[2,the_alias]<sxedia_aliases_addr[1,the_alias] then begin
                                                                           Write_2_Log('ERROR - sxedia_aliases_addr[2,the_alias]<sxedia_aliases_addr[1,the_alias] in alias_is_correct..');
                                                                           retres:=false;
                                                                           goto end_check;
                                                                          end;
end_check:
alias_is_correct:=retres;
end;



procedure Move_Overwrite_Alias_addr(the_alias,change:integer);
var z:integer;
label end_move_alias;
begin
if (the_alias+change>MAX_SXEDIA_PARTS) then begin
                                             Write_2_Log('ERROR - Reached Max sxedia_data in Move_Overwrite_Alias_addr..');
                                             MessageBox (0, 'Εξαντλήσατε τον χώρο καταχωρήσεων.. Ορισμένα από τα στοιχεία προς αποθήκευση δεν είναι δυνατόν να αποθηκευτούν..'+#10+'Επικοινωνήστε με την A-TECH για αναβάθμιση του χώρου αποθηκεύσης..' , ' ', 0 + MB_ICONASTERISK);
                                             goto end_move_alias;
                                            end else
if (the_alias+change<0) then begin
                              Write_2_Log('ERROR - Reached Min sxedia_data..');
                              Error_Occured('Υπήρξε πρόβλημα κατα την αποθήκευση.. Δείτε το log.dat για περισσότερες πληροφορίες');
                              goto end_move_alias;
                             end;

if sxedia_aliases_addr[2,the_alias]<sxedia_aliases_addr[1,the_alias] then begin
                                                                            Write_2_Log('ERROR - BUG - Wrong memory addreses..');
                                                                            MessageBox (0, 'Υπήρξε πρόβλημα κατα την αποθήκευση , δείτε το log για περισσότερες πληροφορίες..'+#10+'Λυπούμαστε πολύ για την αναστάτωση , αναφέρετε το πρόβλημα στην A-TECH..' , ' ', 0 + MB_ICONASTERISK);
                                                                            goto end_move_alias;
                                                                          end;


if change=0 then begin //STUPID CALL :P
                 end else
if change>0 then begin
                  for z:=sxedia_aliases_addr[2,the_alias] downto sxedia_aliases_addr[1,the_alias] do
                    begin
                     sxedia_data[z+change]:=sxedia_data[z];
                    end;
                 end else
if change<0 then begin
                  for z:=sxedia_aliases_addr[1,the_alias] to sxedia_aliases_addr[2,the_alias] do
                    begin
                     sxedia_data[z+change]:=sxedia_data[z];
                    end;
                 end;
end_move_alias:
end;



procedure Add_Plan_Data_2_Alias(the_alias:integer; the_plan:PlanPart);
var i:integer;
begin
if the_alias<aliases_count then
 begin //Metakinisi olwn twn dieythinsewn metepeita aliases mia thesi mprosta :)
  for i:=aliases_count downto the_alias do
    begin
     Move_Overwrite_Alias_addr(i,1);
    end; 
 end;

if sxedia_aliases_addr[2,the_alias]+1>MAX_SXEDIA_PARTS then begin
                                                             Write_2_Log('ERROR - Reached Max sxedia_data in Add_Plan_Data_2_Alias..');
                                                             MessageBox (0, 'Εξαντλήσατε τον χώρο καταχωρήσεων.. Ορισμένα από τα στοιχεία προς αποθήκευση δεν είναι δυνατόν να αποθηκευτούν..'+#10+'Επικοινωνήστε με την A-TECH για αναβάθμιση του χώρου αποθηκεύσης..' , ' ', 0 + MB_ICONASTERISK); 
                                                            end else
                                                            begin
                                                             sxedia_aliases_addr[2,the_alias]:=sxedia_aliases_addr[2,the_alias]+1;
                                                             sxedia_data[sxedia_aliases_addr[2,the_alias]]:=the_plan;
                                                            end;

end;










procedure Remove_Plan_Alias(the_alias:integer);
var i,erase_start,erase_end,backslide:integer;
label end_Remove_Plan_Alias;
begin
erase_start:=sxedia_aliases_addr[1,the_alias];
erase_end:=sxedia_aliases_addr[2,the_alias];
backslide:=erase_end-erase_start+1;

//ERROR CATCHING
if (not (alias_is_correct(the_alias)) ) then begin
                                              Write_2_Log('ERROR occured in Remove_Plan_Alias!');
                                              goto end_Remove_Plan_Alias;
                                             end;
//ERROR CATCHING END :)

clr_tmp_plan;
for i:=erase_start to erase_end do sxedia_data[i]:=tmp_plan; //ERASE ALIAS (MPOREI KAI NA AFERETHEI GIA TAXYTITA++)
for i:=the_alias to aliases_count do
   begin
     sxedia_aliases[i]:=sxedia_aliases[i+1];
     {sxedia_aliases_addr[1,i+1]:=sxedia_aliases_addr[1,i+1]-backslide;
      sxedia_aliases_addr[2,i+1]:=sxedia_aliases_addr[2,i+1]-backslide; }
     sxedia_aliases_addr[1,i]:=sxedia_aliases_addr[1,i+1]-backslide;
     sxedia_aliases_addr[2,i]:=sxedia_aliases_addr[2,i+1]-backslide;
   end;

if erase_end+1<=last_data then
begin //AN YPARXOUN KATAXWRISEIS META TO TELOS NA TOPOTHTITHOUN STIN NEA THESI TOUS..
for i:=erase_end+1 to last_data do
   begin
    sxedia_data[i-backslide]:=sxedia_data[i];
   end;
end;

aliases_count:=aliases_count-1;
Write_2_Log('Removed_Plan_Alias '+Convert2String(the_alias)+'..');
end_Remove_Plan_Alias:

end;


function Add_Plan_Alias(the_alias:string; pointsto:integer):integer;
begin
aliases_count:=aliases_count+1;
if aliases_count<=MAX_SXEDIA then begin
                                        sxedia_aliases[aliases_count]:=the_alias;
                                        sxedia_aliases_addr[1,aliases_count]:=pointsto;
                                      end;
Add_Plan_Alias:=aliases_count;
end;

procedure Add_Alias(the_data:PlanPart);
begin
last_data:=last_data+1;
if last_data<=MAX_SXEDIA_PARTS then sxedia_data[last_data]:=the_data;
end;
 

procedure Compact_Plans;
var the_last_plan,i,z,y:integer;
begin
clr_tmp_plan;
the_last_plan:=0;
if aliases_count>0 then
  begin
    for i:=1 to aliases_count do
       begin
         if sxedia_aliases_addr[1,i]>MAX_SXEDIA_PARTS  then
                                             begin
                                              Write_2_Log('BUG - Address out of bounds , fixing... @'+Convert2String(i)+' = '+Convert2String(sxedia_aliases_addr[1,i])+' - '+Convert2String(sxedia_aliases_addr[2,i]) );
                                              sxedia_aliases_addr[2,i]:=MAX_SXEDIA_PARTS;
                                             end;

         if sxedia_aliases_addr[1,i]<=the_last_plan  then begin
                                                        Write_2_Log('BUG - Bad Address  , fixing... @'+Convert2String(i)+' = '+Convert2String(sxedia_aliases_addr[1,i])+' - '+Convert2String(sxedia_aliases_addr[2,i]) );
                                                        Make_BackUp('Database',the_plan_file); 
                                                        sxedia_aliases_addr[1,i]:=the_last_plan;
                                                      end;

         if sxedia_aliases_addr[1,i]>sxedia_aliases_addr[2,i] then begin
                                                                    Write_2_Log('BUG - Address error while compacting , fixing... @'+Convert2String(i)+' = '+Convert2String(sxedia_aliases_addr[1,i])+' - '+Convert2String(sxedia_aliases_addr[2,i]) );
                                                                    sxedia_aliases_addr[2,i]:=sxedia_aliases_addr[1,i];
                                                                   end;

         if sxedia_aliases_addr[1,i]>the_last_plan+1 then begin
                                                         Write_2_Log('Unused Space Detected.. , compacting... '+sxedia_aliases[i]+' @'+Convert2String(i)+' = '+Convert2String(sxedia_aliases_addr[1,i])+' - '+Convert2String(sxedia_aliases_addr[2,i]) );
                                                         y:=sxedia_aliases_addr[1,i]-the_last_plan-1;
                                                         for z:=sxedia_aliases_addr[1,i] to last_data do
                                                                                        begin 
                                                                                         sxedia_data[z-y]:=sxedia_data[z];
                                                                                         sxedia_data[z]:=tmp_plan;
                                                                                        end;
                                                         for z:=i to aliases_count do begin
                                                                                         sxedia_aliases_addr[1,z]:=sxedia_aliases_addr[1,z]-y;
                                                                                         sxedia_aliases_addr[2,z]:=sxedia_aliases_addr[2,z]-y;
                                                                                        end; 

                                                      end;

        the_last_plan:=sxedia_aliases_addr[2,i];
       end;

  end;
end;

function alias_allocate_free_space_size(the_alias,the_space:integer):integer;
var i:integer;
    needs_push:boolean;
begin
Write_2_Log('Making Space ('+Convert2String(the_space)+') for a data in alias '+sxedia_aliases[the_alias]);
clr_tmp_plan;
needs_push:=true; 
if (the_alias=aliases_count) then needs_push:=false; //DEN XREIAZETAI SPRWKSIMO

if needs_push then
begin
 i:=the_alias+1;
 while i<=aliases_count do begin
                            // SPROXNOUME OLES TIS ANAFORES POU EINAI META APO TIN PROKEIMENI MPROSTA GIA NA XWRESEI..
                            sxedia_aliases_addr[1,i]:=sxedia_aliases_addr[1,i]+the_space;
                            sxedia_aliases_addr[2,i]:=sxedia_aliases_addr[2,i]+the_space;
                            i:=i+1;
                           end;

 i:=last_data; 
 while i>sxedia_aliases_addr[2,the_alias] do
                       begin 
                         sxedia_data[i+the_space]:=sxedia_data[i]; 
                         i:=i-1;
                       end;
end;

sxedia_aliases_addr[2,the_alias]:=sxedia_aliases_addr[2,the_alias]+the_space;   // DIMIOURGOUME ENAN XTRA XWRO STON ALIAS STON OPOIO GINETAI I PROSTHESI..
last_data:=last_data+the_space;  //ENIMERWNOUME TIN GLOBAL METAVLITI..

alias_allocate_free_space_size:=sxedia_aliases_addr[2,the_alias]; 
end;


function Alias_allocate_free_space(the_alias:integer):integer; 
begin
Alias_allocate_free_space:=alias_allocate_free_space_size(the_alias,1);
end;


procedure Load_Person_Plans(filename:string);
var fileused:text;
    bufstr:string;
    tmp:PlanPart;
begin  
aliases_count:=0;
last_data:=0;

assign(fileused,'Database\'+filename);
{$i-}
reset(fileused);
{$i+}
if Ioresult<>0 then MessageBox (0, 'Κενό αρχείο για ανάγνωση σχεδίων θεραπείας....' , ' ', 0) else
begin 
 //OutTextCenter('Loading..'); 
repeat 
   readln(fileused,bufstr); 
   seperate_words(bufstr);  
   if (Equal(get_memory(1),'PLAN_ALIAS')) then  begin
                                                 if aliases_count<>0 then
                                                   begin
                                                    //MessageBox (0, pchar('Ending last_alias '+sxedia_aliases[aliases_count]+' ending @ '+Convert2String(last_data)) , ' ', 0); //
                                                    sxedia_aliases_addr[2,aliases_count]:=last_data; // NA SIMANOUME TO TELOS TOU PROIGOUMENOU ALIAS..
                                                   end;
                                                 Add_Plan_Alias(get_memory(2),last_data+1);
                                                 //MessageBox (0, pchar('Loaded an alias '+get_memory(2)+'Id '+Convert2String(aliases_count)+' starting @ '+Convert2String(last_data+1)) , ' ', 0);
                                                end else
   if (Equal(get_memory(1),'PLAN')) then begin 
                                           tmp.work_id:=get_memory(2); 
                                           tmp.price:=get_memory_int(3);
                                           tmp.discount:=get_memory_int(4);
                                           tmp.prepayment:=get_memory_int(5); 
                                           tmp.dontia:=get_memory(6);
                                           tmp.arithmos_dontiwn:=get_memory_int(7);
                                           tmp.comments:=get_memory(8);
                                           tmp.comments2:=get_memory(9);
                                           tmp.doctor:=get_memory(10);
                                           tmp.explain_file:=get_memory(11);

                                           tmp.dateday:=get_memory_int(12);
                                           tmp.datemonth:=get_memory_int(13);
                                           tmp.dateyear:=get_memory_int(14);
                                           tmp.datehour:=get_memory_int(15);
                                           tmp.datemin:=get_memory_int(16);
                                         //  if Equal(get_memory(17),'1'){2} then tmp.used:=true else
                                                                            //    tmp.used:=false;
                                                                                  tmp.used:=true;
                                           if Equal(get_memory(18),'1'){2} then tmp.date_set:=true else
                                                                                tmp.date_set:=false;
                                           Add_Alias(tmp);
                                           //MessageBox (0, pchar('Added alias to  @ '+Convert2String(last_data)) , ' ', 0);
                                                    
                                         end;
until eof(fileused); 
sxedia_aliases_addr[2,aliases_count]:=last_data; // NA SIMANOUME TO TELOS TOU TELEYTAIOU ALIAS..
if sxedia_aliases_addr[2,aliases_count]<sxedia_aliases_addr[1,aliases_count] then sxedia_aliases_addr[2,aliases_count]:=sxedia_aliases_addr[1,aliases_count]; //AN DN YPARXEI KAMMIA KATAXWRISI STO TELIKO APLA DESMEYOUME MIA THESI
//MessageBox (0, pchar('Ending last_alias '+sxedia_aliases[aliases_count]+' ending @ '+Convert2String(sxedia_aliases_addr[2,aliases_count])) , ' ', 0); //
                                                    
close(fileused); 
end;

end;

procedure Save_Person_Plans(filename:string);
var fileused:text;
    bufstr:string;
    i,z:integer;
begin
assign(fileused,get_central_dir+'Database\'+filename);
rewrite(fileused);
 

if aliases_count>0 then begin
for i:=1 to aliases_count do begin
                              writeln(fileused,'PLAN_ALIAS(',sxedia_aliases[i],')');
                              writeln(fileused,'Last Load Data (',sxedia_aliases_addr[1,i],' - ',sxedia_aliases_addr[2,i],')');
                             if (sxedia_aliases_addr[1,i]<>0) then
                          begin

                              if (alias_is_correct(i)) then
                              begin
                              for z:=sxedia_aliases_addr[1,i] to sxedia_aliases_addr[2,i] do
                                begin
                                 write(fileused,'PLAN(');
                                 write(fileused,sxedia_data[z].work_id,',');
                                 write(fileused,Convert2String(sxedia_data[z].price),',');
                                 write(fileused,Convert2String(sxedia_data[z].discount),',');
                                 write(fileused,Convert2String(sxedia_data[z].prepayment),','); 
                                 write(fileused,sxedia_data[z].dontia,',');
                                 write(fileused,Convert2String(sxedia_data[z].arithmos_dontiwn),','); 
                                 write(fileused,sxedia_data[z].comments,',');
                                 write(fileused,sxedia_data[z].comments2,',');
                                 write(fileused,sxedia_data[z].doctor,',');
                                 write(fileused,sxedia_data[z].explain_file,',');
                                 write(fileused,Convert2String(sxedia_data[z].dateday),',');
                                 write(fileused,Convert2String(sxedia_data[z].datemonth),',');
                                 write(fileused,Convert2String(sxedia_data[z].dateyear),',');
                                 write(fileused,Convert2String(sxedia_data[z].datehour),',');
                                 write(fileused,Convert2String(sxedia_data[z].datemin),',');
                                 if sxedia_data[z].used then write(fileused,'1,') else
                                                             write(fileused,'0,');
                                 if sxedia_data[z].date_set then write(fileused,'1)') else
                                                                 write(fileused,'0)');
                                 writeln(fileused,'');    
                                end;
                              end else
                              Error_Occured('Σφάλμα κατα την αποθήκευση , πρόβλημα με τις διευθύνσεις μνήμης..');

                          end;
                              end;
                       end;  

close(fileused);
end; 

procedure Pass_Plans(thealias,startrecord,endrecord:integer);
var i,y,z,rowsfilled:integer;
    s,bufstr:string;
    label end_pass;
begin 
rowsfilled:=0;
for i:=startrecord to endrecord do
    begin
     s:=Convert2String(i-sxedia_aliases_addr[1,thealias]+1);
     if i-sxedia_aliases_addr[1,thealias]+1<10 then s:='0'+s;
     if get_object_data('use('+s)='3' then rowsfilled:=rowsfilled+1;
    end;


if ((rowsfilled<sxedia_aliases_addr[2,thealias]-sxedia_aliases_addr[1,thealias]+1) and (sxedia_aliases_addr[2,thealias]-sxedia_aliases_addr[1,thealias]<>0)) then
  begin
   i:=MessageBox (0,pchar('Υπάρχουν ορισμένα στοιχεία που έχετε αφήσει αχρησιμοποίητα '+Convert2String(endrecord-startrecord+1-rowsfilled)+'/'+Convert2String(endrecord-startrecord+1)+'..'+#10+' Θέλετε να διαγραφούν?'), ' ', 0 + MB_YESNO + MB_ICONQUESTION +MB_SYSTEMMODAL);
   if i=IDNO then goto end_pass;
  end;

//MessageBox (0, pchar('Detected '+Convert2String(rowsfilled)+' rows filled '), ' ', 0);

// Exoume rowfilled kataxwriseis.. Xwrane ?
while rowsfilled>sxedia_aliases_addr[2,thealias]-sxedia_aliases_addr[1,thealias]+1 do Alias_allocate_free_space(thealias);
// Twra pleon xwrane..

//MessageBox (0, pchar('Saving '+Convert2String(startrecord)+' to '+Convert2String(endrecord)) , ' ', 0);
rowsfilled:=0; 
for i:=startrecord to endrecord do
     begin
     s:=Convert2String(i-sxedia_aliases_addr[1,thealias]+1);
     if i-sxedia_aliases_addr[1,thealias]+1<10 then s:='0'+s; 
     if get_object_data('use('+s)='3' then
         begin
          rowsfilled:=rowsfilled+1;
          z:=sxedia_aliases_addr[1,thealias]+rowsfilled-1;


          //MessageBox (0, pchar('Passing Data from form  '+s+' to '+Convert2String(z)) , ' ', 0);
          sxedia_data[z].work_id:=get_object_data('ergasiaid('+s);
          Val(get_object_data('price('+s),sxedia_data[z].price,y);
          Val(get_object_data('discount('+s),sxedia_data[z].discount,y);
          Val(get_object_data('prepayment('+s),sxedia_data[z].prepayment,y);
          Val(get_object_data('arithmos_dontiwn('+s),sxedia_data[z].arithmos_dontiwn,y);
          sxedia_data[z].comments:=get_object_data('comments('+s);
          sxedia_data[z].dontia:=get_object_data('dontia('+s);
          sxedia_data[z].doctor:=get_object_data('user('+s);
          sxedia_data[z].explain_file:='';//get_object_data('comments2('+s);
          Val(get_object_data('day('+s),sxedia_data[z].dateday,y);
          Val(get_object_data('month('+s),sxedia_data[z].datemonth,y);
          Val(get_object_data('year('+s),sxedia_data[z].dateyear,y);
          Val(get_object_data('hour('+s),sxedia_data[z].datehour,y);
          Val(get_object_data('mins('+s),sxedia_data[z].datemin,y);
          sxedia_data[z].used:=true;
         end; 
     end; 

if ((rowsfilled<sxedia_aliases_addr[2,thealias]-sxedia_aliases_addr[1,thealias]+1) and (sxedia_aliases_addr[2,thealias]-sxedia_aliases_addr[1,thealias]<>0)) then
  begin
   //i:=MessageBox (0,pchar('Υπάρχουν ορισμένα στοιχεία που έχετε αφήσει αχρησιμοποίητα '+Convert2String(endrecord-startrecord+1-rowsfilled)+'/'+Convert2String(endrecord-startrecord+1)+'..'+#10+' Θέλετε να διαγραφούν?'), ' ', 0 + MB_YESNO + MB_ICONQUESTION +MB_SYSTEMMODAL);
   i:=IDYES;
   if i=IDYES then begin
                    Write_2_Log('User choses to discard some elements ');
                    z:=sxedia_aliases_addr[1,thealias]+rowsfilled-1;
                    if ((z>=0) and (z<sxedia_aliases_addr[2,thealias])) then sxedia_aliases_addr[2,thealias]:=z;
                   end;
  end;
Compact_Plans;
end_pass:
end;


procedure clear_row(the_alias,therow:integer);
var s:string; //TO THEROW ERXETAI ETOIMO THEOROUME..
begin
s:=Convert2String(therow);
if therow<10 then s:='0'+s;
//MessageBox (0, pchar('Clearing row '+Convert2String(therow)+' ('+s+')'), ' ', 0);

set_object_data('ergasiaid('+s,'value','',0);
set_object_data('price('+s,'value','',0);
set_object_data('discount('+s,'value','',0);
set_object_data('prepayment('+s,'value','',0);
//set_object_data('doseis('+s,'value','',0);
set_object_data('comments('+s,'value','',0);
set_object_data('day('+s,'value','',0);
set_object_data('month('+s,'value','',0);
set_object_data('year('+s,'value','',0);
set_object_data('day('+s,'value','',0);
set_object_data('hour('+s,'value','',0);
set_object_data('mins('+s,'value','',0);
set_object_data('user('+s,'value','',0);
set_object_data('use('+s,'value','1',0);
set_object_data('dontia('+s,'value','',0);
set_object_data('arithmos_dontiwn('+s,'value','0',0);
end;


function where2addplan(the_alias,fromwhere,towhere:integer):integer;
var i,retres:integer;
    s:string;
begin
retres:=-1;
i:=fromwhere;
while i<=towhere do begin
                     s:=Convert2String(i-sxedia_aliases_addr[1,the_alias]+1);
                     if i-sxedia_aliases_addr[1,the_alias]+1<10 then s:='0'+s;
                     if get_object_data('use('+s)='1' then begin
                                                            retres:=i;
                                                            //MessageBox (0, pchar('ADD to '+Convert2String(i-sxedia_aliases_addr[1,the_alias]+1)) , ' ', 0);
                                                            break;
                                                           end;
                     i:=i+1; 
                    end;
where2addplan:=retres;
end;


function GUI_calender_tools(x,y:integer):integer;
const
  prepare_menu: array[1..2] of AnsiString = (
    'Καταχώρηση στο ημερολόγιο',
    'Επιλογή νέας ημ/νίας'
  );

var //prepare_menu:array [1..2] of string =('Καταχώρηση στο ημερολόγιο','Επιλογή νέας ημ/νίας');
    selection:integer; 
begin
delay(100);
for selection:=1 to 10 do MouseButton(1);
selection:=0;
FlushMouseButtons;
selection:=text_handle_menu(x,y,2,prepare_menu);
GUI_calender_tools:=selection;
end;

function GUI_Open_Plan_Alias(the_alias:integer):string;
var retres,s,theuser,bufstr,lastobj:string;
    winx,winx2,winy,winy2,spacex,formx,priceformx,i,z,x,y:integer;
    startrecord,endrecord:integer;
    datesnstuff:array[1..4]of word;
    appoint_bind:Appointment;
label start_show_data,stop_show_data;
begin
GetLDate(datesnstuff[1],datesnstuff[2],datesnstuff[3],datesnstuff[4]);
theuser:=Get_Current_User; //Oi allages tha apothikeytoun ston..
retres:='';
formx:=TextWidth('XXXXXXXXXXXXXXXXXX');
priceformx:=TextWidth('XXXXXXXX');

 
winx:=GridX(1,8);
winx2:=GridX(7,8);
winy:=GridY(1,15);
winy2:=GridY(14,15);
spacex:=10;

start_show_data:
flush_gui_memory(0);
set_gui_color(ConvertRGB(0,0,0),'comment');
clrscreen;
draw_window;
include_object('window1','window','’νοιγμα σχεδίου εργασιών , '+Convert2String(the_alias)+' '+sxedia_aliases[the_alias],'no','','',winx,winy,winx2,winy2);
draw_all;
delete_object('window1','name');
include_object('namecomment','comment','Όνομα Εργασίας : ','no','','',winx+15,winy+32,0,0);
include_object('name','textbox',sxedia_aliases[the_alias],'no','','',X2(last_object)+5,Y1(last_object),X2(last_object)+formx*2,0);

z:=2;
startrecord:=sxedia_aliases_addr[1,the_alias];
if sxedia_aliases_addr[2,the_alias]>sxedia_aliases_addr[1,the_alias]+5 then endrecord:=sxedia_aliases_addr[2,the_alias] else
endrecord:=sxedia_aliases_addr[1,the_alias]+5;
//MessageBox (0, pchar('Presenting '+Convert2String(startrecord)+' to '+Convert2String(endrecord)) , ' ', 0);
                                                            
SetLineSettings(5,5,5);
for i:=startrecord to endrecord do//sxedia_aliases_addr[1,the_alias] to sxedia_aliases_addr[2,the_alias] do
   begin
     s:=Convert2String(i-sxedia_aliases_addr[1,the_alias]+1);
     if i-sxedia_aliases_addr[1,the_alias]+1<10 then s:='0'+s;
     //ROW1
     include_object('com('+s,'comment','Τμήμα #'+s,'no','','',winx+15,winy+(z+1)*30,0,0);
     include_object('ergasiaid('+s,'textbox',sxedia_data[i].work_id,'no','','',X2(last_object)+spacex,Y1(last_object),X2(last_object)+formx,0);
     include_object('price('+s,'textbox',Convert2String(sxedia_data[i].price),'no','','',X2(last_object)+spacex,Y1(last_object),X2(last_object)+priceformx,0);
     include_object('discount('+s,'textbox',Convert2String(sxedia_data[i].discount),'no','','',X2(last_object)+spacex,Y1(last_object),X2(last_object)+priceformx,0);
     include_object('prepayment('+s,'textbox',Convert2String(sxedia_data[i].prepayment),'no','','',X2(last_object)+spacex,Y1(last_object),X2(last_object)+priceformx,0);
     include_object('arithmos_dontiwn('+s,'textbox',Convert2String(sxedia_data[i].arithmos_dontiwn),'no','','',X2(last_object)+spacex,Y1(last_object),X2(last_object)+priceformx,0);
     include_object('comments('+s,'textbox',sxedia_data[i].comments,'no','','',X2(last_object)+spacex,Y1(last_object),winx2-15,0);
     //ROW2
     include_object('com2('+s,'comment','Ημ.νια :','no','','',winx+15,winy+(z+2)*30,0,0);
     include_object('day('+s,'textbox',Convert2String(sxedia_data[i].dateday),'no','','',X2(last_object)+spacex,Y1(last_object),X2(last_object)+TextWidth('XXX')+spacex,0);
     include_object('/('+s,'comment','/','no','','',X2(last_object)+spacex,Y1(last_object),0,0);
     include_object('month('+s,'textbox',Convert2String(sxedia_data[i].datemonth),'no','','',X2(last_object)+spacex,Y1(last_object),X2(last_object)+TextWidth('XXX')+spacex ,0);
     include_object('//('+s,'comment','/','no','','',X2(last_object)+spacex,Y1(last_object),0,0);
     include_object('year('+s,'textbox',Convert2String(sxedia_data[i].dateyear),'no','','',X2(last_object)+spacex,Y1(last_object),X2(last_object)+TextWidth('XXXXX')+spacex ,0);

     include_object('com3('+s,'comment','Ώρα :','no','','',X2(last_object)+spacex,Y1(last_object),0,0);
     include_object('hour('+s,'textbox',Convert2String(sxedia_data[i].datehour),'no','','',X2(last_object)+spacex,Y1(last_object),X2(last_object)+TextWidth('XXX')+spacex,0);
     include_object(':('+s,'comment',':','no','','',X2(last_object)+spacex,Y1(last_object),0,0);
     include_object('mins('+s,'textbox',Convert2String(sxedia_data[i].datemin),'no','','',X2(last_object)+spacex,Y1(last_object),X2(last_object)+TextWidth('XXX')+spacex ,0);
     
     include_object('com5('+s,'comment','Χρήστης :','no','','',X2(last_object)+spacex,Y1(last_object),0,0);
     include_object('user('+s,'textbox',sxedia_data[i].doctor,'no','','',X2(last_object)+spacex,Y1(last_object),X2(last_object)+TextWidth('XXXXXXXXXXXX')+spacex,0);
     

     include_object('com4('+s,'comment','Χρήση :','no','','',X2(last_object)+spacex,Y1(last_object),0,0);
     include_object('complete('+s,'buttonc','Έγινε','no','','',X1(last_object),Y2(last_object)+3,0,0);

     DrawAPSXY('smalltooth',X2(last_object)+2,Y1(last_object));
     include_object('teeth('+s,'layer','1','no','','',X2(last_object)+2,Y1(last_object),X2(last_object)+2+GetApsInfo('smalltooth','sizex'),Y1(last_object)+GetApsInfo('smalltooth','sizey'));

     DrawAPSXY('smallcalender',X2(last_object)+2,Y1(last_object));
     include_object('calender('+s,'layer','1','no','','',X2(last_object)+2,Y1(last_object),X2(last_object)+2+GetApsInfo('smalltooth','sizex'),Y1(last_object)+GetApsInfo('smalltooth','sizey'));

     if sxedia_data[i].used then bufstr:='3' else
                                 bufstr:='1';  
     include_object('use('+s,'checkbox',bufstr,'no','','',X2('com4('+s)+spacex,Y1('com4('+s),0,0);

     include_object('dontia('+s,'textbox',sxedia_data[i].dontia,'no','','',X2(last_object)+spacex+10,Y1(last_object),winx2-15,0);
     z:=z+3;
     if i-sxedia_aliases_addr[1,the_alias]+1<9 then DrawLine(winx+15,winy+(z)*30+15,winx2-15,winy+(z)*30+15,ConvertRGB(123,123,123));

     if i>sxedia_aliases_addr[2,the_alias] then clear_row(the_alias,i-sxedia_aliases_addr[1,the_alias]+1); //Virtual row (dn antapokrinetai stin pragmatikotita) gi`ayto einai kenos..
   end;
SetLineSettings(1,1,1);
include_object('commprice','comment','Tιμή','no','','',X1('price(01'),winy+65,0,0);
include_object('commdiscount','comment','Έκπτωση','no','','',X1('discount(01'),Y1(last_object),0,0);
include_object('commpayment','comment','Πληρωμή','no','','',X2(last_object)+5,Y1(last_object),0,0);
include_object('commarithmos_dontiwn','comment','x','no','','',X1('arithmos_dontiwn(01')+5,Y1(last_object),0,0); 
include_object('commcomments','comment','Σχόλια','no','','',X1('comments(01')+5,Y1(last_object),0,0);
                         

include_object('new','buttonc','Δημιουργία νέας εργασίας','no','','',winx+15,winy2-40,0,0);
include_object('delete','buttonc','Διαγραφή σχεδίου','no','','',X2(last_object)+5,Y1(last_object),0,0);
include_object('print','buttonc','Εκτύπωση σχεδίου','no','','',X2(last_object)+5,Y1(last_object),0,0);
include_object('antistoixisi','buttonc','Αντιστοίχηση ('+theuser+')','no','','',X2(last_object)+5,Y1(last_object),0,0);
include_object('notes','buttonc','Κοινές Σημειώσεις','no','','',X2(last_object)+5,Y1(last_object),0,0);
include_object('exit','buttonc','Έξοδος','no','','',X2(last_object)+10,Y1(last_object),0,0);
draw_all; 
repeat
interact;
lastobj:=last_object_activated; 
if (get_object_data('delete')='4') then begin
                                         set_object_data('delete','value','1',1);
                                         i:=MessageBox (0, 'Είστε σίγουρος/η οτι θέλετε να διαγράψετε το σχέδιο εργασίας?' , ' ', 0 + MB_YESNO + MB_ICONQUESTION + MB_SYSTEMMODAL);
                                         if i=IDYES then
                                          begin
                                           Remove_Plan_Alias(the_alias);
                                          end; 
                                         goto stop_show_data;
                                        end else
if get_object_data('new')='4' then begin
                                    set_object_data('new','value','1',1);
                                    retres:=get_object_data('name');
                                    Pass_Plans(the_alias,startrecord,endrecord);
                                    i:=where2addplan(the_alias,startrecord,endrecord);
                                    if i<>-1 then
                                      begin
                                       s:=Convert2String(i-sxedia_aliases_addr[1,the_alias]+1);
                                       if i-sxedia_aliases_addr[1,the_alias]+1<10 then s:='0'+s;
                                       bufstr:=Select_Works(false);
                                       if bufstr<>'' then
                                       begin 
                                      // MessageBox (0, pchar('Add 2 '+Convert2String(i)) , ' ', 0 + MB_ICONEXCLAMATION);
                                       while sxedia_aliases_addr[2,the_alias]<i do Alias_allocate_free_space(the_alias);
                                       y:=Get_Work_Mem_From_Code(bufstr);
                                                     if y=-1 then begin
                                                                   MessageBox (0, 'Δεν υπάρχει τιμή για την συγκεκριμένη καταχώρηση - Error' , ' ', 0 + MB_ICONEXCLAMATION);

                                                                 end else
                                                                  begin
                                                                   sxedia_data[i].work_id:=Convert2String(Get_Int_From_Mem(1,y));
                                                                   sxedia_data[i].price:=Get_Int_From_Mem(2,y);
                                                                   sxedia_data[i].comments:=Get_Str_From_Mem(2,y); 
                                                                  end;
                                        sxedia_data[i].discount:=0;
                                        sxedia_data[i].prepayment:=0;
                                      //  sxedia_data[i].doseis:=0;

                                        sxedia_data[i].arithmos_dontiwn:=1;
                                        sxedia_data[i].dontia:='';
                                        sxedia_data[i].doctor:=theuser;
                                        sxedia_data[i].dateday:=datesnstuff[1];
                                        sxedia_data[i].datemonth:=datesnstuff[3];
                                        sxedia_data[i].dateyear:=datesnstuff[4];
                                        sxedia_data[i].datehour:=0;
                                        sxedia_data[i].datemin:=0;
                                        sxedia_data[i].explain_file:=''; // TMP
                                        sxedia_data[i].comments2:='';
                                        sxedia_data[i].used:=true; 
                                        goto start_show_data;
                                       end;
                                        goto start_show_data; //TEST


                                      end else MessageBox (0, 'Πλήρες σχέδιο..' , ' ', 0 + MB_ICONASTERISK);
                                  end else
if (get_object_data('print')='4') then begin
                                        set_object_data('print','value','1',1);
                                        Pass_Plans(the_alias,startrecord,endrecord);
                                        save_graph_window;
                                        clrscreen;
                                        bufstr:=Print_Plan(the_alias);
                                        RunEXE(get_external_browser+' "'+People_Data(0)+'Cache\'+bufstr+'"','normal');
                                        MessageBox (0, 'Πατήστε ΟΚ όταν τελείωσετε με την επεξεργασία του κειμένου..' , ' ', 0);
                                        load_graph_window;
                                        goto start_show_data;
                                       end else
if (get_object_data('notes')='4') then begin
                                        set_object_data('notes','value','1',1);
                                        Pass_Plans(the_alias,startrecord,endrecord);
                                        save_graph_window;
                                        clrscreen;
                                        RunEXE(get_external_editor+' "'+People_Data(0)+'Database\'+People_Data(9)+'.nfo'+'"','normal');
                                        MessageBox (0, 'Πατήστε ΟΚ όταν τελείωσετε με την επεξεργασία του κειμένου..' , ' ', 0);
                                        load_graph_window;
                                        goto start_show_data;
                                       end else
if (get_object_data('antistoixisi')='4') then begin
                                               set_object_data('antistoixisi','value','1',1); 
                                               Pass_Plans(the_alias,startrecord,endrecord);
                                               if (Get_User_Access(Get_Current_User)>=500) then begin
                                                                                                 bufstr:=GUI_Select_User;
                                                                                                 if bufstr<>'' then theuser:=bufstr;
                                                                                                 goto start_show_data;
                                                                                                end else
                                                                        MessageBox (0, 'Χρειάζεται κωδικός μεγαλύτερης πρόσβασης (500+)' , ' ', 0);
                                              end else 
if (lastobj<>'') then                begin
                                      seperate_words(lastobj);
                                       if (get_memory(1)='calender') then begin
                                                                         set_object_data(lastobj,'value','1',1);
                                                                         flush_last_object_activated;
                                                                         Pass_Plans(the_alias,startrecord,endrecord);
                                                                         i:=startrecord+get_memory_int(2)-1;
                                                         if i<=sxedia_aliases_addr[2,the_alias] then
                                                         begin  
                                                           z:=GUI_calender_tools(x1(lastobj),y1(lastobj));
                                                           if ((z=1) and (sxedia_data[i].datemonth<>0) and (sxedia_data[i].dateyear<>0)) then
                                                                    begin
                                                                                if (not (sxedia_data[i].date_set)) then
                                                                                 begin 
                                                                                  sxedia_data[i].date_set:=true;
                                                                                  //MessageBox (0, pchar('SET '+Convert2String(sxedia_data[i].datemonth)+' '+Convert2String(sxedia_data[i].dateyear)), ' ', 0);
                                                                                  appoint_bind.name:=People_Data(2);
                                                                                  appoint_bind.surname:=People_Data(3);
                                                                                  appoint_bind.person_file:=People_Data(8);
                                                                                  appoint_bind.person_handling:=get_object_data('user('+get_memory(2));
                                                                                  appoint_bind.comment:=get_object_data('comments('+get_memory(2));
                                                                                  appoint_bind.appointment_type:=1;
                                                                                  Val(get_object_data('day('+get_memory(2)),z,i);
                                                                                  appoint_bind.dateday:=z;
                                                                                  Val(get_object_data('month('+get_memory(2)),x,i);
                                                                                  appoint_bind.datemonth:=x;
                                                                                  Val(get_object_data('year('+get_memory(2)),y,i);
                                                                                  appoint_bind.dateyear:=y;
                                                                                  Val(get_object_data('hour('+get_memory(2)),appoint_bind.datehour,i);
                                                                                  Val(get_object_data('mins('+get_memory(2)),appoint_bind.datemin,i);
                                                                                  appoint_bind.time_takes:=0;
                                                                                  appoint_bind.used:=true;
                                                                                  Load_Schedule_Month(x,y);
                                                                                  //Load_Schedule_Day_File(Day_Data_Filename(z,x,y),z,x,y);
                                                                                  Add_Schedule_Day(z,appoint_bind);
                                                                                  Save_Schedule_Day_File(Day_Data_Filename(z,x,y),z,x,y);
                                                                                  // TODO... KATI NA GINETAI SET STO CALENDER.. 
                                                                                end else
                                                                                begin
                                                                                 MessageBox (0, 'Η Ημερομηνία αυτού του σχεδίου έχει ήδη περαστεί..' , ' ', 0 + MB_ICONASTERISK);
                                                                                end;
                                                                 end else
                                                           if (z=2) then
                                                                 begin
                                                                   y:=1;
                                                                   Val(get_object_data('day('+get_memory(2)),sxedia_data[i].dateday,x);
                                                                   Val(get_object_data('month('+get_memory(2)),sxedia_data[i].datemonth,x);
                                                                   Val(get_object_data('year('+get_memory(2)),sxedia_data[i].dateyear,x);
                                                                   GUI_select_day_month(sxedia_data[i].dateday,sxedia_data[i].datemonth,sxedia_data[i].dateyear,y); 
                                                                 end;
                                                  end else //Check an ginetai se kapoia asxeti imerominia..
                                                  MessageBox (0, 'Δεν γίνεται να γίνει κάποια ενέργεια σχετικά με το ημερολόγιο γιατι η καταχώρηση δεν χρησιμοποιείται..' , ' ', 0);
                                                                           goto start_show_data;
                                                                        end else
                                       if (get_memory(1)='teeth') then begin
                                                                         set_object_data(lastobj,'value','1',1);
                                                                         flush_last_object_activated;
                                                                         Pass_Plans(the_alias,startrecord,endrecord);
                                                                         i:=startrecord+get_memory_int(2)-1;
                                                                         {sxedia_data[i].dontia:string;
                                                                         arithmos_dontiwn : integer; } 
                                                                        sxedia_data[i].dontia:=select_some_teeth( get_object_data('dontia('+get_memory(2)) , sxedia_data[i].arithmos_dontiwn );
                                                                         goto start_show_data;
                                                                        end else
                                       if (get_memory(1)='complete') then begin
                                                                           set_object_data(lastobj,'value','1',1);
                                                                           flush_last_object_activated;
                                                                           Pass_Plans(the_alias,startrecord,endrecord);  
                                                                           i:=startrecord+get_memory_int(2)-1; 
                                                                           Check_Pass_2_Works(sxedia_data[i].work_id,sxedia_data[i].comments,sxedia_data[i].comments2,sxedia_data[i].doctor,sxedia_data[i].price*sxedia_data[i].arithmos_dontiwn,sxedia_data[i].discount,sxedia_data[i].prepayment,sxedia_data[i].dateday,sxedia_data[i].datemonth,sxedia_data[i].dateyear);
                                                                           goto start_show_data;
                                                                          end else
                                       if ((get_memory_int(2)>=startrecord)and(get_memory_int(2)<=endrecord) and (not (get_memory(1)='use') ) ) then
                                         begin
                                           s:=Convert2String(get_memory_int(2));
                                           if i<10 then s:='0'+s;
                                           if get_object_data('use('+s)='1' then begin
                                                                                  set_object_data('use('+s,'value','3',1);
                                                                                  draw_object_by_name('use('+s);
                                                                                 end;
                                         end;
                                     end;
until GUI_Exit;
Pass_Plans(the_alias,startrecord,endrecord);  
stop_show_data: 
end;


function GUI_New_Plan_Alias:string;
var retres:string;
    formx:integer;
begin
retres:='';
formx:=TextWidth('XXXXXXXXXXXXXXXXXX');
flush_gui_memory(0);
set_gui_color(ConvertRGB(0,0,0),'comment');
clrscreen;
draw_window;

include_object('window1','window','Νέο σχέδιο εργασιών , '+Convert2String(aliases_count)+' συνολικά ','no','','',GridX(1,3),300,GridX(2,3),450);
draw_all;
delete_object('window1','name');
include_object('namecomment','comment','Όνομα Εργασίας : ','no','','',GridX(1,3)+30,360,0,0);
include_object('name','textbox','','no','','',X2(last_object)+10,Y1(last_object),X2(last_object)+formx,0);
include_object('ok','buttonc','Δημιουργία','no','','',GridX(1,3)+30,Y2(last_object)+10,0,0);
include_object('exit','buttonc','Έξοδος','no','','',X2(last_object)+10,Y1(last_object),0,0);
draw_all;
repeat
interact;
if get_object_data('ok')='4' then begin
                                    retres:=get_object_data('name');
                                    set_button('exit',1);
                                  end; 
until GUI_Exit;
GUI_New_Plan_Alias:=retres;
end;



procedure Show_Plans(thefile:string);
var datesnstuff:array[1..4]of word;
    i:integer;
    xc1,yc1,xc2,yc2,bordermiddlx:integer;
    theuser,bufstr,lastobj:string;
    label start_show_plans;
begin
theuser:=Get_Current_User; //Oi allages tha apothikeytoun ston..
GetLDate(datesnstuff[1],datesnstuff[2],datesnstuff[3],datesnstuff[4]); 

xc1:=GridX(1,8);
yc1:=GridY(1,15);
xc2:=GridX(7,8);
yc2:=GridY(14,15);
bordermiddlx:=(xc1+xc2) div 2;

the_plan_file:=thefile+'.plan';

Load_Person_Plans(the_plan_file);
Save_Person_Plans(thefile+'.planbak');

start_show_plans:
flush_gui_memory(0);
set_gui_color(ConvertRGB(0,0,0),'comment');
clrscreen;
draw_window;

include_object('window1','window','Σχέδια Εργασίων , '+Convert2String(aliases_count)+' συνολικά ','no','','',xc1,yc1,xc2,yc2);
draw_all;
delete_object('window1','name');


if aliases_count>0 then
 begin
  for i:=1 to aliases_count do
   begin
    include_object('plan('+Convert2String(i),'buttonc','Σχέδιο #'+Convert2String(i)+'    '+sxedia_aliases[i],'no','','',-1,yc1+i*35,-1,0);
   end;
 end else
include_object('add1st','buttonc','Δεν υπάρχουν σχέδια για τον συγκεκριμένο ασθενή , κάντε click για να δημιουργήσετε','no','','',-1,yc1+100,-1,0);

include_object('add','buttonc','Προσθήκη Σχεδίου','no','','',X1(last_object),yc2-45,0,0);
//include_object('and','buttonc','Αντιστοίχηση KAI','no','','',X2(last_object)+5,Y1(last_object),0,0);
//include_object('or','buttonc','Αντιστοίχηση OR','no','','',X2(last_object)+5,Y1(last_object),0,0);
include_object('exit','buttonc','Έξοδος','no','','',X2(last_object)+5,Y1(last_object),0,0);
draw_all; 
 
repeat
interact; 
lastobj:=return_last_mouse_object; 
if get_object_data('add1st')='4' then begin
                                       set_button('add1st',0);
                                       set_button('add',1); 
                                       last_data:=0;
                                      end;
if get_object_data('add')='4' then begin
                                    set_button('add',0);
                                    bufstr:=GUI_New_Plan_Alias;
                                    if bufstr<>'' then
                                      begin
                                       bufstr:=bufstr+' '+Convert2String(datesnstuff[1])+'/'+Convert2String(datesnstuff[3])+'/'+Convert2String(datesnstuff[4]);
                                       last_data:=last_data+1;
                                       i:=Add_Plan_Alias(bufstr,last_data);
                                       sxedia_aliases_addr[2,aliases_count]:=sxedia_aliases_addr[1,aliases_count]; // ORIZOUME 1 SLOT..
                                      end; 
                                    goto start_show_plans;
                                   end;
 
if get_object_data(lastobj)='4' then begin
                                      if (not (Equal(lastobj,'exit') ) ) then
                                      begin
                                       if ((lastobj<>'')) then seperate_words(lastobj);
                                       if (get_memory(1)='plan') then
                                                                    begin 
                                                                      set_button('exit',1);
                                                                      GUI_Open_Plan_Alias(get_memory_int(2));
                                                                      //break;
                                                                    end;
                                       goto start_show_plans;
                                      end;
                                      end;
until GUI_Exit;
Save_Person_Plans(the_plan_file);




end;






begin
end.
